### PR TITLE
Move task loading code to the end, fixes #1886

### LINKED ISSUE #1886: Can't invoke existing framework rake tasks from custom rakefile
In a rails app I can create a new rake task and have it automatically invoked after another of my chosing by creating a `.rake` file in `lib/tasks` like so:

```ruby
# lib/tasks/secret.rake

namespace :secret do

  task :seriously do
    puts "Shhhhhh! Don't tell anyone!"
  end

  Rake::Task["secret"].enhance do
    Rake::Task["secret:seriously"].invoke
  end

end
```

which can be used like so:

```
$ rake secret
4f877ac845b2af…
Shhhhhh! Don't tell anyone!
````

In a padrino app the same code results in the following error:

```
$ rake secret
rake aborted!
Don't know how to build task 'secret'
lib/tasks/secret.rake:7:in `block in <top (required)>'
lib/tasks/secret.rake:1:in `<top (required)>'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake_tasks.rb:3:in `load'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake_tasks.rb:3:in `block in <top (required)>'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake_tasks.rb:1:in `each'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake_tasks.rb:1:in `<top (required)>'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake.rb:15:in `load'
<gem_dir>/gems/padrino-core-0.12.4/lib/padrino-core/cli/rake.rb:15:in `init'
<app_dir>/Rakefile:6:in `<top (required)>'
<gem_dir>/bin/ruby_executable_hooks:15:in `eval'
<gem_dir>/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

The difference between the two appears to be that in the rails app, `Rake::Task.tasks` returns an array of all the framework and custom tasks, whereas in the padrino app it only includes the tasks defined in that file.

What am I missing to make this work in a padrino app?

### PR DESCRIPTION
**Pull request by namusyaka**

### CODE REVIEW

File: padrino-core/lib/padrino-core/cli/rake_tasks.rb [hunk 1]
```diff
@@ -70,3 +62,11 @@ def env_migration_version
     list_app_routes(app, args) if app
   end
 end
+
+Dir["{lib/tasks/**,tasks/**,test,spec}/*.rake"].each do |file|
```
Comment (sshaw) [inline padrino-core/lib/padrino-core/cli/rake_tasks.rb]: Why even bother loading `test` and `spec` unless we're in the test environment? This alleviates the need to do [this](https://github.com/padrino/padrino-framework/pull/1010/files).

Comment (skade) [inline padrino-core/lib/padrino-core/cli/rake_tasks.rb]: These tasks need to be visible without environment manipulation for discovery reasons.

`rake -T` should _always_ show all tasks, independent of environment variables. Also, `test` and `spec` _activate_ the test environment.

Comment (sshaw) [inline padrino-core/lib/padrino-core/cli/rake_tasks.rb]: > These tasks need to be visible without environment manipulation for discovery reasons.

Discoverable by who and for what? 

> rake -T should always show all tasks, independent of environment variables.

If gem X is included in development and has a task. When I deploy via `bundle install --deployment --without development test` That task is not available via `rake -T`. How is this case different?
